[package]
name = "questdb-jni"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.20.0"
aws-config = "0.54.1"
aws-sdk-s3 = "0.24.0"
tokio = { version = "1", features = ["full"] }
